name: test
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.os }} Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:   ['ubuntu']
        ruby: [ '2.7', '3.0' ]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec parallel_rspec spec/